### ISSUE TITLE
Pixelblaze Instructions slightly unclear

### ISSUE THREAD

**Issue by geekmomprojects** [TheMariday/marimapper#40]
Awesome code and application - thank you so much! Even though I had some trouble getting pipx to work, everything set itself up beautifully from inside VSCode once the virtual environment was in place. 

One minor clarification for the Pixelblaze instructions that might be helpful to others. The instructions say: "upload the marimapper.epe pattern to your Pixelblaze using **marimapper_upload_to_pixelblaze**," but I wasn't able to get that to work (or didn't try hard enough). Pixelblaze already has an established workflow for uploading new patterns, which is to import the .epe file into the Pixelblaze editor and save it as a new pattern. That was much faster and easier for me.

It also wasn't immediately clear to me that the correct argument to "--backend" was "pixelblaze" not "Pixelblaze" (again, super minor, but it's not written anywhere obvious) and that the --server option wants the URL without an "http:" prefix, or it won't work. 

I didn't end up using my laptop's forward-facing only webcam because I found it awkward to point my laptop's screen at the tree I was mapping, so I used an external Logitech USB webcam. It took a bit of digging to realize that the argument to "--device" was an index number (1 for the external camera and 0 for the built-in camera), and I wasn't sure of what kind of values I should pass in to the --exposure and --threshold arguments to get them to work. Again, super minor, but some example range values for those arguments would be a time saver in getting the code to work for the first time.

I also didn't realize the rapidly and significantly diminishing returns for doing more than a few mappings to get coordinates, though I figured it out by repeatedly checking the 3D CSV file. In the end, about 50 of my 600 pixel coordinates were unmapped, but were extremely easy to generate within an excel spreadsheet using the "LOOKUP" function to average from nearest neighbors.

Once again, these are all trivial details that I just wanted to pass along. I really loved using this fantastic (can't believe it's free!) mapper, and I will be using it again in the future. Thank you so much!!!

**Comment by TheMariday** [comment]
Hi there! Thank you so much for the feedback! It's really helpful in not only this but helping me write better code!

Just put in a commit to address some of these: 59e05639ac181409169fd00307d968c915d581a5

I would love to know what went wrong with PIPx for you just for reference if you have time as it should be able to do what we're asking of it. (opened a separate ticket [here](https://github.com/TheMariday/marimapper/issues/42))

I actually have never run MariMapper myself on a pixelblaze system so I'm sorry that there have been issues there. I've added a warning about `marimapper_upload_to_pixelblaze` and added instructions on uploading it rather than using the tool. I've also opened a separate ticket to look at why this [might not be working](https://github.com/TheMariday/marimapper/issues/41).

I've also added a .lower() to the backend parser so that it's more tolerant to capitalisation.

Quick question on the PixelBlaze server, does it need a port? like `192.168.4.1:8000` or just `192.168.4.1`

I've also added some docs around the `--device`, `--exposure` and `--threshold` as well as made sure that when using `--help` it prints out the defaults for all arguments.

Printing out how many LEDs the reconstructor has currently found is a bit tricky, but I will keep it in mind for future development.

Also with the nearest neighbour thing, MariMapper already has this built in! it's set to 5 by default so I'm wondering if either that's not enough or if it's not working correctly.

In the meantime I've added `--max_fill` to allow you to adjust the number of leds to fill.

So glad I can be of help and thank you for taking the time to summarize your experience so concisely!
