### ISSUE TITLE
Crash on scan?

### ISSUE THREAD

**Issue by Spritetm** [TheMariday/marimapper#45]
I'm scanning my Christmas tree, as one does, but I can't get the 3d window to pop up. Instead, I get some segfault as soon as some LEDs can be reconstructed. I'll copy-paste the relevant log below. Scanning can continue after the segfault, and more scan csvs get written if I do so, but no 3d reconstruction takes place.

I'm running Python 3.11 under Debian; installed marimapper using pipx. No clue if you can figure out what is wrong, but I have little experience with Python and I'm scratching my head here, so I hope this rings a bell.

[DEBUG/FileWriterProcess-3] Queue._after_fork()
[INFO/FileWriterProcess-3] child process calling self.run()
[DEBUG/DetectorProcess-1] Queue._start_thread()
[DEBUG/DetectorProcess-1] doing self._thread.start()
[DEBUG/DetectorProcess-1] starting thread to feed data to pipe
[DEBUG/DetectorProcess-1] ... done self._thread.start()
[INFO/DetectorProcess-1] Connecting to device 4 ...
[DEBUG/MainProcess] scanner initialised
Start scan? [y/n]: [DEBUG/DetectorProcess-1] Connected to device 4 with capture method 200
[DEBUG/SFM-2] sfm managed to reconstruct 17 leds
[DEBUG/SFM-2] filled 13 LEDs
*** Aborted at 1734014736 (unix time) try "date -d @1734014736" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x7f69d11fe540) received by PID 12519 (TID 0x7f6a44247080) from PID 18446744072923112768; stack trace: ***
    @     0x7f6a0e29adfe (unknown)
    @     0x7f6a44287d20 (unknown)
    @     0x7f6a214cb927 (unknown)
    @     0x7f6a214c1861 GOMP_parallel
    @     0x7f6a048cf551 (unknown)
    @     0x7f6a048a1cff (unknown)
    @     0x7f6a020587f0 (unknown)
    @     0x7f6a01fbd0b6 (unknown)
    @           0x4d599b (unknown)
    @           0x481a61 _PyObject_MakeTpCall
    @           0x424bf0 _PyEval_EvalFrameDefault
    @           0x5835b8 (unknown)
    @           0x4831f9 _PyObject_Call_Prepend
    @           0x4f899b (unknown)
    @           0x4f0b17 (unknown)
    @           0x481a61 _PyObject_MakeTpCall
    @           0x424bf0 _PyEval_EvalFrameDefault
    @           0x5835b8 (unknown)
    @           0x4831f9 _PyObject_Call_Prepend
    @           0x4f899b (unknown)
    @           0x4f0b17 (unknown)
    @           0x481a61 _PyObject_MakeTpCall
    @           0x424bf0 _PyEval_EvalFrameDefault
    @           0x583454 PyEval_EvalCode
    @           0x5cf631 (unknown)
    @           0x5d0ccf _PyRun_SimpleFileObject
    @           0x5d12d0 _PyRun_AnyFileObject
    @           0x5f29b0 (unknown)
    @           0x5f303e Py_BytesMain
    @     0x7f6a44271d68 (unknown)
    @     0x7f6a44271e25 __libc_start_main
    @           0x42c191 _start

**Comment by TheMariday** [comment]
Hi there. I'm so sorry you've had this issue. This is usually due to pycolmap.

Could you paste or send somehow your CSV files please so I can test it?

Thank you!

**Comment by Spritetm** [comment]
Sure, see attached. Note I tried two separate scan sessions (with the csvs deleted inbetween) and it did it both times, so I'm not 100% sure the csvs have something to do with it, but who knows.
[csv_files.tar.gz](https://github.com/user-attachments/files/18113459/csv_files.tar.gz)

**Comment by TheMariday** [comment]
Hi there, I have a quick fix for you and will put in a proper fix soon.

Re-install marimapper by downloading this repo, and installing it with pip install -e.

In sfm_process.py, comment out add_normals(leds_3d)

This will probably break the visualiser but will still output the 3D map to file.

So sorry this is affecting you and I will get a proper fix to you soon.

**Comment by Spritetm** [comment]
Thanks, that netted me a virtual version of my christmas tree! No need to be sorry, btw; I appreciate you putting this piece of software out there to begin with as well as helping me get a workaround at such short notice.

**Comment by TheMariday** [comment]
Hi @Spritetm

I'm so glad you got something working. I spent some time today chasing this down and I have put in a permanent fix.

Upgrading to MariMapper v2.2 should work (with `pipx upgrade marimapper` or if you've already installed with `pip install -e .` then just doing a fresh pull).

It would be awesome if you could verify that it's working if you have the time but no problem if not.

Turns out that Windows and Mac by default, start multiprocesses with a spawn method, but Linux uses fork.

For some weird reason, [Open3D can only calculate normals in a spawn](https://github.com/isl-org/Open3D/issues/6425#issuecomment-1757645866)????? So the scanner cli script now forces multiprocessing into spawn mode which makes it more consistent.

This wasn't picked up by CI as the code is split into implementation and multiprocessing wrapper and I was only testing the implementation.

I've added a single test to verify that:
- The break is detectable by CI
- Forcing spawn mode fixes it.

I've also raised an issue to look into calculate normals as this isn't the first time it's caused some issues (strange dependency quirks)

https://github.com/TheMariday/marimapper/issues/46

Anyway this is probably way more information than you need but thought I'd update you incase you were curious.

**Comment by Spritetm** [comment]
It seems perfectly happy now, thanks! Wow, that is a crazy Open3D error, thanks for managing to track it down as the cause of the issue.
